apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: especifica-cpu-memory
spec:
  validationFailureAction: Enforce
  rules:
    - name: revisa-los-recursos-aplicados
      match:
        resources:
          kinds:
            - Pod
            - Deployment
      validate:
        message: "Debe establecer requests y limits de CPU y memoria."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
